// AUTO-GENERATED by scripts/generate-frontend-contracts.ts — do not edit.
// Wire contract types derived from src/builder/contracts.ts (TypeBox schemas).
// Regenerate with: pnpm contracts:frontend

export interface ApiField {
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly required?: boolean;
  readonly unique?: boolean;
  readonly indexed?: boolean;
  readonly enumValues?: readonly string[];
}

export interface ApiResource {
  readonly id: string;
  readonly name: string;
  readonly plural?: string;
  readonly description?: string;
  readonly fields: readonly {
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly required?: boolean;
  readonly unique?: boolean;
  readonly indexed?: boolean;
  readonly enumValues?: readonly string[];
}[];
  readonly relations?: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
  readonly targetResource: string;
  readonly foreignKey?: string;
}[];
  readonly indexes?: readonly {
  readonly id: string;
  readonly name: string;
  readonly fields: readonly string[];
  readonly unique?: boolean;
}[];
}

export interface ApiEndpoint {
  readonly id: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly summary?: string;
  readonly parameters?: readonly {
  readonly id: string;
  readonly name: string;
  readonly in: "path" | "query" | "header" | "cookie";
  readonly type: string;
  readonly required?: boolean;
}[];
  readonly requestBody?: {
  readonly resource?: string;
};
  readonly responses?: readonly {
  readonly status: number;
  readonly description?: string;
  readonly resource?: string;
}[];
  readonly policyIds?: readonly string[];
  readonly capabilityBinding?: string;
}

export interface ApiPolicy {
  readonly id: string;
  readonly name: string;
  readonly effect: "allow" | "deny";
  readonly action: string;
  readonly resource?: string;
}

export interface ApiOperation {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
}

export interface ApiEvent {
  readonly id: string;
  readonly name: string;
}

export interface ApiDefinition {
  readonly id: string;
  readonly name: string;
  readonly namespace: string;
  readonly version: string;
  readonly status: string;
  readonly resources: readonly {
  readonly id: string;
  readonly name: string;
  readonly plural?: string;
  readonly description?: string;
  readonly fields: readonly {
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly required?: boolean;
  readonly unique?: boolean;
  readonly indexed?: boolean;
  readonly enumValues?: readonly string[];
}[];
  readonly relations?: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
  readonly targetResource: string;
  readonly foreignKey?: string;
}[];
  readonly indexes?: readonly {
  readonly id: string;
  readonly name: string;
  readonly fields: readonly string[];
  readonly unique?: boolean;
}[];
}[];
  readonly endpoints: readonly {
  readonly id: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly summary?: string;
  readonly parameters?: readonly {
  readonly id: string;
  readonly name: string;
  readonly in: "path" | "query" | "header" | "cookie";
  readonly type: string;
  readonly required?: boolean;
}[];
  readonly requestBody?: {
  readonly resource?: string;
};
  readonly responses?: readonly {
  readonly status: number;
  readonly description?: string;
  readonly resource?: string;
}[];
  readonly policyIds?: readonly string[];
  readonly capabilityBinding?: string;
}[];
  readonly policies: readonly {
  readonly id: string;
  readonly name: string;
  readonly effect: "allow" | "deny";
  readonly action: string;
  readonly resource?: string;
}[];
  readonly operations: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
}[];
  readonly events: readonly {
  readonly id: string;
  readonly name: string;
}[];
  readonly revision: number;
  readonly metadata: {
  readonly description?: string;
  readonly tags?: readonly string[];
  readonly author?: string;
  readonly createdAt: string;
  readonly updatedAt: string;
};
}

export interface CreateDefinitionInput {
  readonly name: string;
  readonly namespace: string;
  readonly version: string;
  readonly description?: string;
  readonly tags?: readonly string[];
  readonly author?: string;
}

export interface UpdateDefinitionInput {
  readonly name?: string;
  readonly namespace?: string;
  readonly version?: string;
  readonly resources?: readonly {
  readonly id: string;
  readonly name: string;
  readonly plural?: string;
  readonly description?: string;
  readonly fields: readonly {
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly required?: boolean;
  readonly unique?: boolean;
  readonly indexed?: boolean;
  readonly enumValues?: readonly string[];
}[];
  readonly relations?: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
  readonly targetResource: string;
  readonly foreignKey?: string;
}[];
  readonly indexes?: readonly {
  readonly id: string;
  readonly name: string;
  readonly fields: readonly string[];
  readonly unique?: boolean;
}[];
}[];
  readonly endpoints?: readonly {
  readonly id: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly summary?: string;
  readonly parameters?: readonly {
  readonly id: string;
  readonly name: string;
  readonly in: "path" | "query" | "header" | "cookie";
  readonly type: string;
  readonly required?: boolean;
}[];
  readonly requestBody?: {
  readonly resource?: string;
};
  readonly responses?: readonly {
  readonly status: number;
  readonly description?: string;
  readonly resource?: string;
}[];
  readonly policyIds?: readonly string[];
  readonly capabilityBinding?: string;
}[];
  readonly policies?: readonly {
  readonly id: string;
  readonly name: string;
  readonly effect: "allow" | "deny";
  readonly action: string;
  readonly resource?: string;
}[];
  readonly operations?: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
}[];
  readonly events?: readonly {
  readonly id: string;
  readonly name: string;
}[];
}

export interface ValidationIssue {
  readonly path: string;
  readonly message: string;
  readonly severity: "error" | "warning";
}

export interface ValidationResult {
  readonly ok: boolean;
  readonly issues: readonly {
  readonly path: string;
  readonly message: string;
  readonly severity: "error" | "warning";
}[];
}

export interface Contract {
  readonly hash: string;
  readonly compilerVersion: string;
  readonly openapi: unknown;
  readonly routes: readonly unknown[];
}

export interface CompatibilityChange {
  readonly kind: string;
  readonly path: string;
  readonly severity: "breaking" | "compatible" | "info";
  readonly message: string;
}

export interface Compatibility {
  readonly classification: "compatible" | "breaking" | "unknown";
  readonly changes: readonly {
  readonly kind: string;
  readonly path: string;
  readonly severity: "breaking" | "compatible" | "info";
  readonly message: string;
}[];
}

export interface PreviewResult {
  readonly definition: {
  readonly id: string;
  readonly name: string;
  readonly namespace: string;
  readonly version: string;
  readonly status: string;
  readonly resources: readonly {
  readonly id: string;
  readonly name: string;
  readonly plural?: string;
  readonly description?: string;
  readonly fields: readonly {
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly required?: boolean;
  readonly unique?: boolean;
  readonly indexed?: boolean;
  readonly enumValues?: readonly string[];
}[];
  readonly relations?: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
  readonly targetResource: string;
  readonly foreignKey?: string;
}[];
  readonly indexes?: readonly {
  readonly id: string;
  readonly name: string;
  readonly fields: readonly string[];
  readonly unique?: boolean;
}[];
}[];
  readonly endpoints: readonly {
  readonly id: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly summary?: string;
  readonly parameters?: readonly {
  readonly id: string;
  readonly name: string;
  readonly in: "path" | "query" | "header" | "cookie";
  readonly type: string;
  readonly required?: boolean;
}[];
  readonly requestBody?: {
  readonly resource?: string;
};
  readonly responses?: readonly {
  readonly status: number;
  readonly description?: string;
  readonly resource?: string;
}[];
  readonly policyIds?: readonly string[];
  readonly capabilityBinding?: string;
}[];
  readonly policies: readonly {
  readonly id: string;
  readonly name: string;
  readonly effect: "allow" | "deny";
  readonly action: string;
  readonly resource?: string;
}[];
  readonly operations: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
}[];
  readonly events: readonly {
  readonly id: string;
  readonly name: string;
}[];
  readonly revision: number;
  readonly metadata: {
  readonly description?: string;
  readonly tags?: readonly string[];
  readonly author?: string;
  readonly createdAt: string;
  readonly updatedAt: string;
};
};
  readonly validation: {
  readonly ok: boolean;
  readonly issues: readonly {
  readonly path: string;
  readonly message: string;
  readonly severity: "error" | "warning";
}[];
};
  readonly contract: {
  readonly hash: string;
  readonly compilerVersion: string;
  readonly openapi: unknown;
  readonly routes: readonly unknown[];
};
  readonly compatibility: {
  readonly classification: "compatible" | "breaking" | "unknown";
  readonly changes: readonly {
  readonly kind: string;
  readonly path: string;
  readonly severity: "breaking" | "compatible" | "info";
  readonly message: string;
}[];
};
  readonly publishable: boolean;
}

export interface Revision {
  readonly definition: {
  readonly id: string;
  readonly name: string;
  readonly namespace: string;
  readonly version: string;
  readonly status: string;
  readonly resources: readonly {
  readonly id: string;
  readonly name: string;
  readonly plural?: string;
  readonly description?: string;
  readonly fields: readonly {
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly required?: boolean;
  readonly unique?: boolean;
  readonly indexed?: boolean;
  readonly enumValues?: readonly string[];
}[];
  readonly relations?: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
  readonly targetResource: string;
  readonly foreignKey?: string;
}[];
  readonly indexes?: readonly {
  readonly id: string;
  readonly name: string;
  readonly fields: readonly string[];
  readonly unique?: boolean;
}[];
}[];
  readonly endpoints: readonly {
  readonly id: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly summary?: string;
  readonly parameters?: readonly {
  readonly id: string;
  readonly name: string;
  readonly in: "path" | "query" | "header" | "cookie";
  readonly type: string;
  readonly required?: boolean;
}[];
  readonly requestBody?: {
  readonly resource?: string;
};
  readonly responses?: readonly {
  readonly status: number;
  readonly description?: string;
  readonly resource?: string;
}[];
  readonly policyIds?: readonly string[];
  readonly capabilityBinding?: string;
}[];
  readonly policies: readonly {
  readonly id: string;
  readonly name: string;
  readonly effect: "allow" | "deny";
  readonly action: string;
  readonly resource?: string;
}[];
  readonly operations: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
}[];
  readonly events: readonly {
  readonly id: string;
  readonly name: string;
}[];
  readonly revision: number;
  readonly metadata: {
  readonly description?: string;
  readonly tags?: readonly string[];
  readonly author?: string;
  readonly createdAt: string;
  readonly updatedAt: string;
};
};
  readonly compiledHash: string;
  readonly recordedAt: string;
}

export interface ListDefinitionsResult {
  readonly items: readonly {
  readonly id: string;
  readonly name: string;
  readonly namespace: string;
  readonly version: string;
  readonly status: string;
  readonly resources: readonly {
  readonly id: string;
  readonly name: string;
  readonly plural?: string;
  readonly description?: string;
  readonly fields: readonly {
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly required?: boolean;
  readonly unique?: boolean;
  readonly indexed?: boolean;
  readonly enumValues?: readonly string[];
}[];
  readonly relations?: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
  readonly targetResource: string;
  readonly foreignKey?: string;
}[];
  readonly indexes?: readonly {
  readonly id: string;
  readonly name: string;
  readonly fields: readonly string[];
  readonly unique?: boolean;
}[];
}[];
  readonly endpoints: readonly {
  readonly id: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly summary?: string;
  readonly parameters?: readonly {
  readonly id: string;
  readonly name: string;
  readonly in: "path" | "query" | "header" | "cookie";
  readonly type: string;
  readonly required?: boolean;
}[];
  readonly requestBody?: {
  readonly resource?: string;
};
  readonly responses?: readonly {
  readonly status: number;
  readonly description?: string;
  readonly resource?: string;
}[];
  readonly policyIds?: readonly string[];
  readonly capabilityBinding?: string;
}[];
  readonly policies: readonly {
  readonly id: string;
  readonly name: string;
  readonly effect: "allow" | "deny";
  readonly action: string;
  readonly resource?: string;
}[];
  readonly operations: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
}[];
  readonly events: readonly {
  readonly id: string;
  readonly name: string;
}[];
  readonly revision: number;
  readonly metadata: {
  readonly description?: string;
  readonly tags?: readonly string[];
  readonly author?: string;
  readonly createdAt: string;
  readonly updatedAt: string;
};
}[];
  readonly nextCursor: string | null;
  readonly total: number;
}

export interface PublishResult {
  readonly definition: {
  readonly id: string;
  readonly name: string;
  readonly namespace: string;
  readonly version: string;
  readonly status: string;
  readonly resources: readonly {
  readonly id: string;
  readonly name: string;
  readonly plural?: string;
  readonly description?: string;
  readonly fields: readonly {
  readonly id: string;
  readonly name: string;
  readonly type: string;
  readonly required?: boolean;
  readonly unique?: boolean;
  readonly indexed?: boolean;
  readonly enumValues?: readonly string[];
}[];
  readonly relations?: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: "one-to-one" | "one-to-many" | "many-to-one" | "many-to-many";
  readonly targetResource: string;
  readonly foreignKey?: string;
}[];
  readonly indexes?: readonly {
  readonly id: string;
  readonly name: string;
  readonly fields: readonly string[];
  readonly unique?: boolean;
}[];
}[];
  readonly endpoints: readonly {
  readonly id: string;
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  readonly path: string;
  readonly summary?: string;
  readonly parameters?: readonly {
  readonly id: string;
  readonly name: string;
  readonly in: "path" | "query" | "header" | "cookie";
  readonly type: string;
  readonly required?: boolean;
}[];
  readonly requestBody?: {
  readonly resource?: string;
};
  readonly responses?: readonly {
  readonly status: number;
  readonly description?: string;
  readonly resource?: string;
}[];
  readonly policyIds?: readonly string[];
  readonly capabilityBinding?: string;
}[];
  readonly policies: readonly {
  readonly id: string;
  readonly name: string;
  readonly effect: "allow" | "deny";
  readonly action: string;
  readonly resource?: string;
}[];
  readonly operations: readonly {
  readonly id: string;
  readonly name: string;
  readonly kind: string;
}[];
  readonly events: readonly {
  readonly id: string;
  readonly name: string;
}[];
  readonly revision: number;
  readonly metadata: {
  readonly description?: string;
  readonly tags?: readonly string[];
  readonly author?: string;
  readonly createdAt: string;
  readonly updatedAt: string;
};
};
  readonly operationId: string;
}

export interface Error {
  readonly error: {
  readonly code: string;
  readonly message: string;
  readonly requestId: string;
  readonly correlationId: string;
  readonly retryable: boolean;
  readonly details?: unknown;
};
}
