export type { ImageArchitecture, BaseSystemProfile, BootProfile, SystemProfile, LoginProfile, OnboardingProfile, DesktopProfile, PackageProfile, SecurityProfile, RecoveryProfile, ApplicationProfile, VestaraImageProfile, ImageBuildTarget } from './domain/profile.js';
export { hashImageProfile, withProfileHash } from './domain/profile.js';
export { ImageProfileRegistry, DESKTOP_PROFILE, SERVER_PROFILE } from './domain/registry.js';
export type { ImageBuildStage, ImageBuildStatus, ImageBuildState } from './domain/lifecycle.js';
export { stageOrder, stageIndex } from './domain/lifecycle.js';
export type { BuildPlanItem, ImageBuildPlan } from './domain/build-plan.js';
export { compileBuildPlan } from './domain/build-plan.js';
export type { FirmwareKind, TpmMode, HardwareDeviceSpec, HardwareTarget } from './domain/hardware.js';
export { hardwareTargetCatalog, resolveHardwareTarget } from './domain/hardware.js';
export type { PartitionTableType, PartitionKind, PartitionFilesystem, PartitionEncryption, PartitionDefinition, PartitionLayout, PartitionLayoutIssue, PartitionLayoutValidation } from './domain/partitions.js';
export { validatePartitionLayout, defaultDesktopLayout } from './domain/partitions.js';
export type { ImageProfileLifecycleStatus, ImageProfileLifecycle, ImageProfileTransition } from './domain/lifecycle-profile.js';
export { canTransition, nextStatus, initialLifecycle, advanceLifecycle } from './domain/lifecycle-profile.js';
export type { LockedPackage, PackageResolutionRequest, PackageResolutionResult } from './domain/package-lock.js';
export { resolvePackages } from './domain/package-lock.js';
export type { BuildPlanV2Item, BuildPlanWarning, BuildPlanV2Input, ImageBuildPlanV2 } from './domain/build-plan-v2.js';
export { compileBuildPlanV2 } from './domain/build-plan-v2.js';
export type { PreflightVerdict, PreflightItem, PreflightResult, PreflightContext } from './domain/preflight.js';
export { runPreflight } from './domain/preflight.js';
export type { BuildRunStatus, BuildStageStatus, BuildStageRun, BuildRun, BuildRunStorePort } from './domain/build-run.js';
export { BuildRunController, InMemoryBuildRunStore } from './domain/build-run.js';
export type { ImageRootfsPort, BootstrapResult, BootstrapAdapter, PackageInstaller, ImagePackagePort, ApplyResult } from './adapters/build-ports.js';
export type { ImageBuildServiceOptions, ImageBuildResult } from './service/image-build-service.js';
export { ImageBuildService } from './service/image-build-service.js';
export type { ImagePlatformV2Options } from './service/image-platform-v2.js';
export { ImagePlatformV2 } from './service/image-platform-v2.js';
