export type { SystemRiskLevel, SystemOperationKind, SystemCapabilityDefinition } from './domain/capabilities.js';
export { SYSTEM_CAPABILITIES, getSystemCapability, hasSystemCapability, FORBIDDEN_SYSTEM_OPERATIONS } from './domain/capabilities.js';
export type { BootEntry, BootEntrySource, BootOrder } from './domain/boot.js';
export { createBootOrder } from './domain/boot.js';
export type { SlotId, SlotHealth, SlotState } from './domain/slots.js';
export { createSlotState, isSlotHealthy } from './domain/slots.js';
export type { DetectionStatus, FirmwareMode, CpuInfo, MemoryInfo, StorageInfo, NetworkInfo, HardwareDiscovery, FirmwareInfo, SystemDiscoveryResult } from './discovery/types.js';
export type { SystemDiscoveryPort } from './discovery/port.js';
export { EnvironmentSystemDiscovery } from './adapters/environment.js';
export type { RecoveryDestination, RecoveryBootRequest, RecoveryBootControl, PowerAction, PowerControlRequest, PowerControl } from './service/controls.js';
export type { SystemServiceOptions } from './service/system-service.js';
export { SystemService } from './service/system-service.js';
export type { DetectionStatus as InventoryDetectionStatus, SystemIdentity, OperatingSystemInfo, CpuSubsystem, MemorySubsystem, StorageDeviceInfo, StorageSubsystem, FilesystemInfo, FilesystemSubsystem, NetworkInterfaceInfo, NetworkSubsystem, GraphicsDeviceInfo, GraphicsSubsystem, HardwareDeviceInfo, DeviceSubsystem, PowerInfo, PowerSubsystem, ThermalInfo, ThermalSubsystem, KernelSubsystem, BootState, SystemSnapshot, SystemInventoryPort, SystemInventorySection } from './inventory/domain.js';
export { inventorySections } from './inventory/domain.js';
export { EnvironmentSystemInventory } from './inventory/environment.js';
export type { ServiceStatus, ServiceOperation, ServiceInfo, ProcessInfo, ServiceManagerPort } from './runtime/services.js';
export { SystemdServiceManager, EnvironmentServiceManager } from './runtime/services.js';
export type { KernelModuleInfo, KernelInfo, DependencyEdge, DependencyGraph } from './runtime/kernel.js';
export { discoverKernel, buildDependencyGraph, dependenciesOf, dependentsOf } from './runtime/kernel.js';
export type { StorageMutationKind, MountInfo, StorageManagerPort } from './runtime/storage.js';
export { StorageManager, EnvironmentStorageManager, STORAGE_MUTATION_RISK } from './runtime/storage.js';
export type { SystemOperationRequest, SystemOperationStatus, SystemOperationJournalEntry, SystemOperationStorePort, SystemOperationExecutorPort } from './service/system-operations.js';
export { SYSTEM_OPERATION_RISK, SystemOperationBroker, InMemorySystemOperationStore, DevSystemOperationExecutor } from './service/system-operations.js';
export type { SystemV2Options } from './service/system-v2-service.js';
export { SystemV2Service } from './service/system-v2-service.js';
