// AUTO-GENERATED by scripts/generate-frontend-contracts.ts — do not edit.
// Wire contract types derived from src/image/contracts.ts (TypeBox schemas).
// Regenerate with: pnpm contracts:frontend

export type Architecture = "amd64" | "arm64";

export interface BaseSystemProfile {
  readonly distribution: "debian";
  readonly release: string;
  readonly kernel: string;
}

export interface BootProfile {
  readonly grub: {
  readonly enabled: boolean;
  readonly timeout: number;
  readonly theme?: string;
};
  readonly plymouth: {
  readonly enabled: boolean;
  readonly theme: string;
};
  readonly firmwareLogo: {
  readonly mode: "runtime-if-supported" | "none";
};
}

export interface SystemProfile {
  readonly abSlots: boolean;
  readonly recovery: boolean;
}

export interface LoginProfile {
  readonly provider: "vestara";
  readonly password: boolean;
  readonly fingerprint: "auto" | "disabled";
  readonly fido2: "auto" | "disabled";
}

export interface OnboardingProfile {
  readonly firstBoot: boolean;
}

export interface DesktopProfile {
  readonly session: "vestara" | "fallback";
  readonly startupApp: string;
  readonly desktopApp: string;
}

export interface PackageProfile {
  readonly extraPackages: readonly string[];
}

export interface SecurityProfile {
  readonly noDefaultOwner: boolean;
  readonly sanitizeSecrets: boolean;
}

export interface RecoveryProfile {
  readonly enabled: boolean;
  readonly includes: readonly string[];
}

export interface ApplicationProfile {
  readonly applications: readonly string[];
}

export interface ImageProfile {
  readonly id: string;
  readonly version: string;
  readonly architecture: "amd64" | "arm64";
  readonly base: {
  readonly distribution: "debian";
  readonly release: string;
  readonly kernel: string;
};
  readonly boot: {
  readonly grub: {
  readonly enabled: boolean;
  readonly timeout: number;
  readonly theme?: string;
};
  readonly plymouth: {
  readonly enabled: boolean;
  readonly theme: string;
};
  readonly firmwareLogo: {
  readonly mode: "runtime-if-supported" | "none";
};
};
  readonly system: {
  readonly abSlots: boolean;
  readonly recovery: boolean;
};
  readonly applications: {
  readonly applications: readonly string[];
};
  readonly onboarding: {
  readonly firstBoot: boolean;
};
  readonly login: {
  readonly provider: "vestara";
  readonly password: boolean;
  readonly fingerprint: "auto" | "disabled";
  readonly fido2: "auto" | "disabled";
};
  readonly desktop: {
  readonly session: "vestara" | "fallback";
  readonly startupApp: string;
  readonly desktopApp: string;
};
  readonly packages: {
  readonly extraPackages: readonly string[];
};
  readonly security: {
  readonly noDefaultOwner: boolean;
  readonly sanitizeSecrets: boolean;
};
  readonly recovery: {
  readonly enabled: boolean;
  readonly includes: readonly string[];
};
  readonly profileHash: string;
}

export interface UpdateImageProfileInput {
  readonly version?: string;
  readonly architecture?: "amd64" | "arm64";
  readonly base?: {
  readonly distribution: "debian";
  readonly release: string;
  readonly kernel: string;
};
  readonly boot?: {
  readonly grub: {
  readonly enabled: boolean;
  readonly timeout: number;
  readonly theme?: string;
};
  readonly plymouth: {
  readonly enabled: boolean;
  readonly theme: string;
};
  readonly firmwareLogo: {
  readonly mode: "runtime-if-supported" | "none";
};
};
  readonly system?: {
  readonly abSlots: boolean;
  readonly recovery: boolean;
};
  readonly applications?: {
  readonly applications: readonly string[];
};
  readonly onboarding?: {
  readonly firstBoot: boolean;
};
  readonly login?: {
  readonly provider: "vestara";
  readonly password: boolean;
  readonly fingerprint: "auto" | "disabled";
  readonly fido2: "auto" | "disabled";
};
  readonly desktop?: {
  readonly session: "vestara" | "fallback";
  readonly startupApp: string;
  readonly desktopApp: string;
};
  readonly packages?: {
  readonly extraPackages: readonly string[];
};
  readonly security?: {
  readonly noDefaultOwner: boolean;
  readonly sanitizeSecrets: boolean;
};
  readonly recovery?: {
  readonly enabled: boolean;
  readonly includes: readonly string[];
};
}

export interface ImageBuildPlanItem {
  readonly stage: string;
  readonly description: string;
  readonly generated: readonly string[];
}

export interface ImageBuildPlan {
  readonly profileId: string;
  readonly profileHash: string;
  readonly target: "raw" | "installer" | "virtual";
  readonly items: readonly {
  readonly stage: string;
  readonly description: string;
  readonly generated: readonly string[];
}[];
  readonly planHash: string;
}

export interface ImageBuildState {
  readonly buildId: string;
  readonly status: "draft" | "planning" | "building" | "verifying" | "completed" | "failed";
  readonly currentStage?: string;
  readonly completedStages: readonly string[];
  readonly failedStage?: string;
  readonly failureMessage?: string;
  readonly startedAt?: string;
  readonly completedAt?: string;
}

export interface ImageBuildResult {
  readonly state: {
  readonly buildId: string;
  readonly status: "draft" | "planning" | "building" | "verifying" | "completed" | "failed";
  readonly currentStage?: string;
  readonly completedStages: readonly string[];
  readonly failedStage?: string;
  readonly failureMessage?: string;
  readonly startedAt?: string;
  readonly completedAt?: string;
};
  readonly plan: {
  readonly profileId: string;
  readonly profileHash: string;
  readonly target: "raw" | "installer" | "virtual";
  readonly items: readonly {
  readonly stage: string;
  readonly description: string;
  readonly generated: readonly string[];
}[];
  readonly planHash: string;
};
  readonly evidence: {
  readonly planHash: string;
  readonly artifactPath: string;
  readonly evidenceHash: string;
};
}

export interface PlanRequest {
  readonly profileId: string;
  readonly target: "raw" | "installer" | "virtual";
}

export interface BuildRequest {
  readonly profileId: string;
  readonly target: "raw" | "installer" | "virtual";
  readonly approved: boolean;
}
