// AUTO-GENERATED by scripts/generate-frontend-contracts.ts — do not edit.
// Wire contract types derived from src/ai/contracts.ts (TypeBox schemas).
// Regenerate with: pnpm contracts:frontend

export interface AiConsumer {
  readonly type: "module" | "agent" | "workflow" | "service" | "user";
  readonly id: string;
}

export interface AiMessage {
  readonly role: "system" | "user" | "assistant" | "tool";
  readonly content: string | readonly {
  readonly type: string;
  readonly value: string;
  readonly mediaType?: string;
}[];
  readonly name?: string;
  readonly toolCalls?: readonly {
  readonly id: string;
  readonly name: string;
  readonly arguments: string;
}[];
  readonly toolCallId?: string;
}

export interface AiToolCall {
  readonly id: string;
  readonly name: string;
  readonly arguments: string;
}

export interface AiToolDefinition {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: unknown;
}

export interface AiGenerateRequest {
  readonly consumer: {
  readonly type: "module" | "agent" | "workflow" | "service" | "user";
  readonly id: string;
};
  readonly model: {
  readonly provider: string;
  readonly model: string;
} | {
  readonly requirements: {
  readonly reasoning?: boolean;
  readonly tools?: boolean;
  readonly structuredOutput?: boolean;
  readonly functionCalling?: boolean;
  readonly vision?: boolean;
  readonly embeddings?: boolean;
  readonly input?: readonly string[];
  readonly minContext?: number;
};
  readonly optimizeFor?: string;
};
  readonly messages: readonly {
  readonly role: "system" | "user" | "assistant" | "tool";
  readonly content: string | readonly {
  readonly type: string;
  readonly value: string;
  readonly mediaType?: string;
}[];
  readonly name?: string;
  readonly toolCalls?: readonly {
  readonly id: string;
  readonly name: string;
  readonly arguments: string;
}[];
  readonly toolCallId?: string;
}[];
  readonly system?: string;
  readonly tools?: readonly {
  readonly name: string;
  readonly description: string;
  readonly inputSchema: unknown;
}[];
  readonly output?: {
  readonly schema: unknown;
};
  readonly temperature?: number;
  readonly maxTokens?: number;
  readonly fallbackCount?: number;
}

export interface AiGenerateResult {
  readonly content: string;
  readonly modelId: string;
  readonly providerId: string;
  readonly usage: {
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly cachedTokens?: number;
  readonly estimatedCostUsd?: number;
};
  readonly latencyMs: number;
  readonly fallbackCount: number;
  readonly toolCalls?: readonly {
  readonly id: string;
  readonly name: string;
  readonly arguments: string;
}[];
}

export type AiStreamEvent = {
  readonly type: "chunk";
  readonly text: string;
} | {
  readonly type: "tool-call";
  readonly toolCall: {
  readonly id: string;
  readonly name: string;
  readonly arguments: string;
};
} | {
  readonly type: "done";
  readonly modelId: string;
  readonly providerId: string;
  readonly usage: {
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly cachedTokens?: number;
  readonly estimatedCostUsd?: number;
};
} | {
  readonly type: "error";
  readonly message: string;
};

export interface AiUsage {
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly cachedTokens?: number;
  readonly estimatedCostUsd?: number;
}

export interface AiUsageRecord {
  readonly requestId: string;
  readonly consumerId: string;
  readonly providerId: string;
  readonly modelId: string;
  readonly inputTokens: number;
  readonly outputTokens: number;
  readonly cachedTokens?: number;
  readonly estimatedCostUsd?: number;
  readonly latencyMs: number;
  readonly startedAt: string;
  readonly completedAt: string;
  readonly fallbackCount: number;
}
