export type { DashboardScope, WidgetLoadState, WidgetSize, WidgetPlacement, DashboardLayout, DashboardDataSource, DashboardWidgetDefinition, WidgetInstance } from './domain/widget.js';
export type { DashboardProjectionDefinition, ProjectionResult, DashboardFilter, DashboardFilterOperator, RefreshPolicy, DashboardDefinition } from './domain/dashboard.js';
export type { DashboardContribution, DashboardContributionSource, ModuleLifecyclePort } from './domain/contribution.js';
export type { DashboardValidationIssue, DashboardValidationResult } from './domain/dashboard-validation.js';
export { DashboardValidator, bumpDashboardRevision } from './domain/dashboard-validation.js';
export type { WidgetRegistryOptions } from './registry/widget-registry.js';
export { DashboardWidgetRegistry } from './registry/widget-registry.js';
export type { DashboardStorePort } from './store/dashboard-store.js';
export { InMemoryDashboardStore } from './store/dashboard-store.js';
export type { ProjectionProvider, ProjectionProviderOptions } from './service/projection-service.js';
export { ProjectionService } from './service/projection-service.js';
export type { DashboardServiceOptions } from './service/dashboard-service.js';
export { DashboardService } from './service/dashboard-service.js';
export type { SystemProjectionData, TaskProjectionData, AgentProjectionData, WorkflowProjectionData, DiagnosticProjectionData, DatabaseProjectionData, NotificationProjectionData } from './contributions/builtin.js';
export { systemDashboardContribution, taskDashboardContribution, agentDashboardContribution, workflowDashboardContribution, diagnosticsDashboardContribution, databaseDashboardContribution, notificationDashboardContribution, allDashboardContributions } from './contributions/builtin.js';
export type { BuilderSessionState, DashboardDraft, WidgetPlacementChange, BuilderOperation } from './builder/dashboard-builder-session.js';
export { DashboardBuilderSession, emptyDefinition } from './builder/dashboard-builder-session.js';
export type { DashboardBuilderOptions } from './builder/dashboard-builder-service.js';
export { DashboardBuilderService } from './builder/dashboard-builder-service.js';
export type { DashboardGenerationTarget, DashboardGenerationPlan, DashboardGenerationInput, DashboardGenerationResult } from './builder/dashboard-generator.js';
export { DashboardGenerator } from './builder/dashboard-generator.js';
