import type { TemplateDefinition } from '../domain/template-definition.js';

/** TPL-013..018 — first-party templates across kinds. */
export function builtinTemplates(): readonly TemplateDefinition[] {
  return [
    {
      id: 'template.dashboard.engineering',
      name: 'Engineering Dashboard',
      version: '1.0.0',
      kind: 'dashboard',
      description: 'Engineering activity: tasks, agents, workflows, tests, diagnostics.',
      tags: ['engineering', 'dashboard'],
      parameters: [
        { name: 'projectName', type: 'string', required: true, description: 'Project name' },
        { name: 'includeTests', type: 'boolean', defaultValue: true },
        { name: 'includeAgents', type: 'boolean', defaultValue: true },
        { name: 'refreshInterval', type: 'number', defaultValue: 30 },
      ],
      definition: {
        name: '{{parameters.projectName}} Dashboard',
        scope: 'workspace',
        widgetTypes: ['system.health', 'tasks.my-tasks', 'workflow.activity'],
        includeTests: '{{parameters.includeTests}}',
        includeAgents: '{{parameters.includeAgents}}',
        refreshInterval: '{{parameters.refreshInterval}}',
      },
      recommendedThemeId: 'vestara.dark',
      requiredCapabilities: ['task.read', 'system.read'],
      metadata: { version: '1.0.0', tags: ['engineering'] },
    },
    {
      id: 'template.dashboard.operations',
      name: 'Operations Dashboard',
      version: '1.0.0',
      kind: 'dashboard',
      description: 'System + database + diagnostics health.',
      tags: ['operations', 'dashboard'],
      parameters: [{ name: 'projectName', type: 'string', required: true }],
      definition: {
        name: '{{parameters.projectName}} Operations',
        scope: 'system',
        widgetTypes: ['system.resources', 'database.health', 'diagnostics.health'],
      },
      recommendedThemeId: 'vestara.light',
      requiredCapabilities: ['system.read', 'database.read', 'diagnostics.read'],
      metadata: { version: '1.0.0', tags: ['operations'] },
    },
    {
      id: 'template.page.crud',
      name: 'CRUD Page',
      version: '1.0.0',
      kind: 'page',
      description: 'A list + create/edit dialog page for a resource.',
      tags: ['page', 'crud'],
      parameters: [
        { name: 'resource', type: 'string', required: true },
        { name: 'route', type: 'string', required: true },
      ],
      definition: {
        name: '{{parameters.resource}}',
        route: '{{parameters.route}}',
        nodes: [{ component: 'data-grid', binding: '{{parameters.resource}}.list' }],
      },
      requiredCapabilities: [],
      metadata: { version: '1.0.0', tags: ['page'] },
    },
    {
      id: 'template.application.admin',
      name: 'Admin Platform',
      version: '1.0.0',
      kind: 'application',
      description: 'Admin platform with users, pages, dashboards and auth.',
      tags: ['application', 'admin'],
      parameters: [
        { name: 'applicationName', type: 'string', required: true },
        { name: 'applicationType', type: 'enum', defaultValue: 'web', enumValues: ['web', 'dashboard', 'system'] },
      ],
      definition: {
        name: '{{parameters.applicationName}}',
        applicationType: '{{parameters.applicationType}}',
        modules: ['user', 'authentication', 'database', 'dashboard'],
      },
      recommendedThemeId: 'vestara.dark',
      requiredCapabilities: ['application.read'],
      metadata: { version: '1.0.0', tags: ['application'] },
    },
    {
      id: 'template.agent.coding',
      name: 'Coding Agent',
      version: '1.0.0',
      kind: 'agent',
      description: 'A coding agent with file/git/browser tools.',
      tags: ['agent', 'coding'],
      parameters: [{ name: 'agentName', type: 'string', required: true }],
      definition: {
        name: '{{parameters.agentName}}',
        tools: ['file.read', 'file.search', 'git.status', 'browser.navigate'],
        model: 'default',
      },
      requiredCapabilities: ['file.read', 'git.read'],
      metadata: { version: '1.0.0', tags: ['agent'] },
    },
    {
      id: 'template.os-image.desktop',
      name: 'Desktop OS Image',
      version: '1.0.0',
      kind: 'os-image',
      description: 'Vestara desktop OS image profile.',
      tags: ['os-image', 'desktop'],
      parameters: [
        { name: 'hostname', type: 'string', required: true },
        { name: 'timezone', type: 'string', defaultValue: 'UTC' },
      ],
      definition: {
        hostname: '{{parameters.hostname}}',
        timezone: '{{parameters.timezone}}',
        desktop: 'vestara',
        abSlots: true,
        recovery: true,
      },
      requiredCapabilities: ['image.read'],
      metadata: { version: '1.0.0', tags: ['os-image'] },
    },
  ];
}
