/** IMG-043/044 — Generator-integrated boot artifact generation. */

import { hashOf } from '../../generator/domain/hash.js';
import type { VestaraImageProfile } from './profile.js';
import type { HardwareTarget } from './hardware.js';

export type BootArtifactKind =
  | 'grub-config'
  | 'plymouth-theme'
  | 'systemd-unit'
  | 'login-config'
  | 'desktop-config'
  | 'network-config'
  | 'initramfs-config'
  | 'service-manifest'
  | 'kernel-params'
  | 'application-manifest';

export interface BootArtifact {
  readonly kind: BootArtifactKind;
  readonly path: string;
  readonly content: string;
  readonly generatedBy: string;
  readonly artifactHash: string;
}

export interface BootArtifactRequest {
  readonly profile: VestaraImageProfile;
  readonly hardware: HardwareTarget;
  readonly stage: string;
}

/**
 * IMG-043/044 — Boot artifact generation. Each build stage requests artifacts
 * from the Generator (GRUB, Plymouth, systemd, login, desktop, network,
 * services, app manifests). Generate != Write: generation produces desired
 * artifacts; the image apply port owns writes.
 */
export function generateBootArtifacts(request: BootArtifactRequest): readonly BootArtifact[] {
  const { profile, hardware, stage } = request;
  const artifacts: BootArtifact[] = [];

  const grubTheme = profile.boot.grub.theme ?? 'vestara-dark';
  const grubConfig = [
    '# Generated by Vestara Image Builder (IMG-043)',
    `set default="0"`,
    `set timeout=${profile.boot.grub.timeout}`,
    `set theme=/${grubTheme}/theme.txt`,
    `menuentry "Vestara OS" {`,
    `  search --fs-uuid --set=root ${'VESTARA-A'}`,
    `  linux /boot/vmlinuz root=/dev/mapper/vestara-a ${hardware.kernelModules.map((m) => `modprobe=${m}`).join(' ')}`,
    `  initrd /boot/initrd.img`,
    `}`,
  ].join('\n');
  artifacts.push({
    kind: 'grub-config',
    path: `/boot/grub/grub.cfg`,
    content: grubConfig,
    generatedBy: 'generator/grub',
    artifactHash: hashOf(grubConfig),
  });

  const plymouth = `[Theme]\nName=${profile.boot.plymouth.theme}\nModuleName=script`;
  artifacts.push({
    kind: 'plymouth-theme',
    path: `/usr/share/plymouth/themes/${profile.boot.plymouth.theme}/theme.conf`,
    content: plymouth,
    generatedBy: 'generator/plymouth',
    artifactHash: hashOf(plymouth),
  });

  const systemdUnit = [
    '[Unit]',
    'Description=Vestara Platform Target',
    'After=systemd-user-sessions.service',
    'Requires=vestara-startup.service',
    '[Install]',
    'WantedBy=graphical.target',
  ].join('\n');
  artifacts.push({
    kind: 'systemd-unit',
    path: `/etc/systemd/system/vestara.target`,
    content: systemdUnit,
    generatedBy: 'generator/systemd',
    artifactHash: hashOf(systemdUnit),
  });

  const loginConfig = `[Login]\nprovider=${profile.login.provider}\npassword=${profile.login.password}\nfingerprint=${profile.login.fingerprint}\nfido2=${profile.login.fido2}`;
  artifacts.push({
    kind: 'login-config',
    path: `/etc/vestara/login.conf`,
    content: loginConfig,
    generatedBy: 'generator/login',
    artifactHash: hashOf(loginConfig),
  });

  const kernelParams = `console=ttyS0 quiet ${hardware.kernelModules.join(' ')}`;
  artifacts.push({
    kind: 'kernel-params',
    path: `/etc/default/vestara-kernel-params`,
    content: kernelParams,
    generatedBy: 'generator/kernel',
    artifactHash: hashOf(kernelParams),
  });

  const appManifest = JSON.stringify({ applications: profile.applications.applications }, null, 2);
  artifacts.push({
    kind: 'application-manifest',
    path: `/etc/vestara/applications.json`,
    content: appManifest,
    generatedBy: 'generator/applications',
    artifactHash: hashOf(appManifest),
  });

  if (stage === 'configure-firstboot') {
    const onboarding = JSON.stringify({ firstBoot: profile.onboarding.firstBoot }, null, 2);
    artifacts.push({
      kind: 'service-manifest',
      path: `/etc/vestara/onboarding.json`,
      content: onboarding,
      generatedBy: 'generator/onboarding',
      artifactHash: hashOf(onboarding),
    });
  }

  return artifacts;
}
