import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import * as TypeBox from '@sinclair/typebox';
import {
  ApiDefinitionSchema,
  ApiEndpointSchema,
  ApiEventSchema,
  ApiFieldSchema,
  ApiOperationSchema,
  ApiPolicySchema,
  ApiResourceSchema,
  CompatibilityChangeSchema,
  CompatibilitySchema,
  ContractSchema,
  CreateDefinitionBody,
  ErrorSchema,
  ListDefinitionsResultSchema,
  PreviewResultSchema,
  PublishResultSchema,
  RevisionSchema,
  UpdateDefinitionBody,
  ValidationResultSchema,
} from '../src/builder/contracts.js';

const OUTPUT = resolve('vestara-apps', 'api-builder', 'src', 'api', 'contracts.ts');

const SCHEMAS: Record<string, TypeBox.TSchema> = {
  ApiField: ApiFieldSchema,
  ApiResource: ApiResourceSchema,
  ApiEndpoint: ApiEndpointSchema,
  ApiPolicy: ApiPolicySchema,
  ApiOperation: ApiOperationSchema,
  ApiEvent: ApiEventSchema,
  ApiDefinition: ApiDefinitionSchema,
  CreateDefinitionInput: CreateDefinitionBody,
  UpdateDefinitionInput: UpdateDefinitionBody,
  ValidationIssue: (ValidationResultSchema as TypeBox.TObject).properties.issues
    .items as TypeBox.TSchema,
  ValidationResult: ValidationResultSchema,
  Contract: ContractSchema,
  CompatibilityChange: CompatibilityChangeSchema,
  Compatibility: CompatibilitySchema,
  PreviewResult: PreviewResultSchema,
  Revision: RevisionSchema,
  ListDefinitionsResult: ListDefinitionsResultSchema,
  PublishResult: PublishResultSchema,
  Error: ErrorSchema,
};

function typeName(t: TypeBox.TSchema): string {
  switch (t[TypeBox.Kind]) {
    case 'String':
      return 'string';
    case 'Boolean':
      return 'boolean';
    case 'Integer':
    case 'Number':
      return 'number';
    case 'Null':
      return 'null';
    case 'Any':
      return 'unknown';
    case 'Array':
      return `readonly ${typeName((t as TypeBox.TArray).items)}[]`;
    case 'Literal':
      return JSON.stringify((t as TypeBox.TLiteral).const);
    case 'Union': {
      const union = t as TypeBox.TUnion;
      return union.anyOf.map((member) => typeName(member)).join(' | ');
    }
    case 'Object': {
      const obj = t as TypeBox.TObject;
      const required = obj.required ?? [];
      const props = Object.entries(obj.properties).map(([key, value]) => {
        const optional = required.includes(key) ? '' : '?';
        return `  readonly ${key}${optional}: ${typeName(value)};`;
      });
      return `{\n${props.join('\n')}\n}`;
    }
    default:
      return 'unknown';
  }
}

function emitInterface(name: string, schema: TypeBox.TSchema): string {
  const obj = schema as TypeBox.TObject;
  const required = obj.required ?? [];
  const props = Object.entries(obj.properties).map(([key, value]) => {
    const optional = required.includes(key) ? '' : '?';
    return `  readonly ${key}${optional}: ${typeName(value)};`;
  });
  return `export interface ${name} {\n${props.join('\n')}\n}`;
}

function emit(): string {
  const lines: string[] = [
    '// AUTO-GENERATED by scripts/generate-frontend-contracts.ts — do not edit.',
    '// Wire contract types derived from src/builder/contracts.ts (TypeBox schemas).',
    '// Regenerate with: pnpm contracts:frontend',
    '',
  ];
  for (const name of Object.keys(SCHEMAS)) {
    lines.push(emitInterface(name, SCHEMAS[name]!));
    lines.push('');
  }
  return lines.join('\n');
}

async function main(): Promise<void> {
  await mkdir(resolve(OUTPUT, '..'), { recursive: true });
  await writeFile(OUTPUT, emit(), 'utf8');
  // eslint-disable-next-line no-console
  console.log(`Frontend contracts generated → ${OUTPUT}`);
}

void main();
