import { ArtifactSet } from '../generator/artifacts/artifact-set.js';
import { createGenerationPlan } from '../generator/domain/plan.js';
import { hashOf } from '../generator/domain/hash.js';
import type { Generator, GenerationContext } from '../generator/domain/contracts.js';
import { GeneratorRegistry } from '../generator/registry/generator-registry.js';
import { GenerationService } from '../generator/service/generation-service.js';
import { substitutionRenderer, type TemplateDefinition } from '../generator/templates/template-registry.js';
import { createConfigurationSnapshot, type ResolvedConfigValue } from '../generator/context/configuration-snapshot.js';
import type { ConfigurationService } from '../configuration/service/configuration-service.js';

export interface SdkGeneratorInput {
  readonly apiName: string;
  readonly endpoints: readonly { method: string; path: string; operationId?: string }[];
}

interface SdkGeneratorOutput {
  readonly apiName: string;
  readonly endpointCount: number;
}

const SDK_TEMPLATES: Record<string, TemplateDefinition> = {
  'generator.api.typescript.index': {
    id: 'generator.api.typescript.index',
    version: '1.0.0',
    source: [
      '// {{ apiName }} client — generated by @vestara/generator-api',
      'export const apiName = "{{ apiName }}";',
      'export const endpoints = [',
      '{{ endpoints }}',
      '];',
    ].join('\n'),
  },
};

class TypescriptSdkGenerator implements Generator<SdkGeneratorInput, SdkGeneratorOutput> {
  readonly id = 'generator.api.typescript';
  readonly version = '1.0.0';
  readonly capabilities = ['generator.api', 'generator.sdk.typescript', 'templates'];
  readonly requiresSecrets = false;

  async plan(input: SdkGeneratorInput) {
    return createGenerationPlan({
      id: `plan-${this.id}`,
      generatorId: this.id,
      inputHash: hashOf(input),
      steps: [
        { id: 'render-index', kind: 'render', description: 'Render the index.ts client' },
        { id: 'assemble', kind: 'assemble', description: 'Assemble the artifact set', dependencies: ['render-index'] },
      ],
      requirements: [
        { id: 'api-name', label: 'API name is provided', satisfied: input.apiName.trim().length > 0 },
        { id: 'endpoints', label: 'At least one endpoint', satisfied: input.endpoints.length > 0 },
      ],
    });
  }

  async generate(input: SdkGeneratorInput, context: GenerationContext) {
    const artifacts = new ArtifactSet(this.id, this.version);
    const template = context.templates['generator.api.typescript.index'] as TemplateDefinition;
    const endpoints = input.endpoints
      .map((e) => `  { method: "${e.method}", path: "${e.path}" }`)
      .join(',\n');
    const rendered = substitutionRenderer(template, {
      values: { apiName: input.apiName, endpoints },
    });
    artifacts.add({ path: 'index.ts', content: rendered, kind: 'typescript' });
    return {
      artifacts,
      output: { apiName: input.apiName, endpointCount: input.endpoints.length },
    };
  }
}

export interface GeneratorBootstrapResult {
  readonly registry: GeneratorRegistry;
  readonly service: GenerationService;
  readonly templates: Readonly<Record<string, TemplateDefinition>>;
}

export function buildGeneratorPlatform(): GeneratorBootstrapResult {
  const registry = new GeneratorRegistry();
  registry.register(new TypescriptSdkGenerator());
  const templates = { ...SDK_TEMPLATES };
  const service = new GenerationService({ registry, templates });
  return { registry, service, templates };
}

/** Build a ConfigurationSnapshot from the Configuration service's resolved values. */
export function snapshotFromConfiguration(configuration: ConfigurationService): ReturnType<typeof createConfigurationSnapshot> {
  const resolved: ResolvedConfigValue[] = configuration.resolveAll().map((r) => ({
    key: r.key,
    value: r.value,
    scope: r.scope,
    secret: r.secret,
  }));
  return createConfigurationSnapshot(resolved);
}
